name: deploy flask project.

# Hello world! Run this to push

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

 
jobs:
  
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{secrets.SSH_USERNAME}}
          server: ${{secrets.SSH_HOST}}
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # will put all file under this path
          local_path: ./* 
          # files will copy to under remote_path
          remote_path: /home/CD_Stefan/
          # sftp args
          args: '-o ConnectTimeout=5'