name: Checkout Repository

on: push
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      # Checkout Repository, now lives in $GITHUB_REPOSITORY
      - name: Checkout repository
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      # Install PyTest and Flask
      - name: Install Dependencies
        run: pip install -r requirements.txt
      # Run the tests
      - name: Run-tests
        run: pytest
      # Add SSH Key
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder'
      # Add it to known hosts
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # Copy dist folder with Rsync
      - name: Deploy with Rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/CD_Stefan
      # Restart the application
      - name: Restart Application
        run: ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl restart CD_Stefan
