name: deploy flask project.

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run-tests
        run: pytest
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with Rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/
      - name: Restart Application
        run: ssh -t ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} 'sudo systemctl restart CD_Stefan
