name: deploy flask project.

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run-tests
        run: pytest

      deploy:
      runs-on: ubuntu-20.04
      needs: Run-tests # this job depends on "test" having finished
      steps:
        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USERNAME}}
            key:  ${{secrets.SSH_PRIVATE_KEY}} 
            port: ${{secrets.PORT}}
            script: 
              cd ..
              cd /home/CD_Stefan/
              git pull
              systemctl restart cd
        
